// Oracle adapter (DISABLED)
//
// unified-system now runs a Notion-only backend. The previous Oracle adapter pulled
// in the `oracledb` dependency, which can cause Vercel serverless cold-start/import
// failures even when Oracle routes are not used.
//
// This stub is kept to avoid breaking any lingering imports, but all Oracle
// operations are intentionally unavailable.

export const ORACLE_DISABLED_MESSAGE =
  'Oracle support is disabled; unified-system uses a Notion-only backend.';

function oracleDisabled() {
  throw new Error(ORACLE_DISABLED_MESSAGE);
}

// No-op: callers often invoke this in finally blocks.
export async function closePool() {
  return;
}

export async function initializePool() {
  oracleDisabled();
}

export async function getConnection() {
  oracleDisabled();
}

export async function executeQuery() {
  oracleDisabled();
}

export async function withOracleConnection() {
  oracleDisabled();
}

export async function withOracleTransaction() {
  oracleDisabled();
}

export function createBindOut() {
  oracleDisabled();
}

export async function healthCheck() {
  return false;
}

// Some diagnostic endpoints referenced this helper; keep a safe placeholder.
export function getResolvedConnectInfo() {
  return { disabled: true, reason: ORACLE_DISABLED_MESSAGE };
}

// Keep conversion helpers (pure functions; do not require oracledb).
export function convertParameterStyle(sql) {
  return String(sql).replace(/\$(\d+)/g, (_match, num) => `:${num}`);
}

export function convertSQLToOracle(sql) {
  let oracleSQL = convertParameterStyle(sql);

  oracleSQL = oracleSQL
    .replace(/SERIAL/gi, 'NUMBER GENERATED BY DEFAULT AS IDENTITY')
    .replace(/BOOLEAN/gi, 'NUMBER(1)')
    .replace(/TEXT/gi, 'CLOB')
    .replace(/NOW\(\)/gi, 'CURRENT_TIMESTAMP')
    .replace(/LIMIT\s+(\d+)/gi, 'FETCH FIRST $1 ROWS ONLY')
    .replace(/ILIKE/gi, 'LIKE')
    .replace(/~~\*/gi, 'LIKE')
    .replace(/!~~\*/gi, 'NOT LIKE');

  return oracleSQL;
}

// Backwards-compat: some files imported `{ oracledb }` for constants.
export const oracledb = undefined;

